POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImEyMiIsImlkIjoiNWVmYjBjZWJlOTEyYjdkODlkMGE3NTdkIiwiaWF0IjoxNTkzNTE5OTk0fQ.2ccM1VWEnvwEL8JermiUsnOAzzvOyE3yt73Ul5zejWY

{
    "title": "3",
	"author": "3",
	"url": "3.com",
	"likes": 3
}